### PR TITLE
Add blog to navbar

### PR DESCRIPTION
**Pull request by josh146**
* Adds the blog to the navbar
* Fixes the buggy green underline when the navbar is collapsed

### CODE REVIEW

**Comment by josh146** [comment]
I've made this same PR across most of the repos, but only tagged this one for review. Once it's approved, I'll copy the changes to all the others :)

**Comment by josh146** [comment]
Should we replace the 'Hack' card on the landing page with something else now that QHack is over?

**Comment by glassnotes** [comment]
There is a noticeable style change when switching to the blog; can the navbar be made consistent size and font with the main page (even if some of the fonts in the blog contents are different?)

Peek 2021-04-13 09-44

**Comment by glassnotes** [comment]
> Should we replace the 'Hack' card on the landing page with something else now that QHack is over?

Yes I think so - what was there before, was it a link to the docs?

(Should keep it in the navbar though? I think it looks kinda nice!)

**Comment by josh146** [comment]
> (Should keep it in the navbar though? I think it looks kinda nice!)

:+1:

**Comment by glassnotes** [comment]
> Make it a link to the blog?

I like that idea - what if we called it "explore", or "discover" or something? ("read" would also work but sounds more boring)

**Comment by josh146** [comment]
@glassnotes the navbar issue should now be fixed, more or less :)

**Review by co9olguy — APPROVED** [review]

**Review by glassnotes — APPROVED** [review]

**Comment by josh146** [comment]
@co9olguy @glassnotes, this now has the 👌 to be merged in. Should we do it now, or are we waiting on something else?

**Comment by glassnotes** [comment]
I think it's good to go, unless you wanted to replace the QHack card (but that can always be done separately).

**Comment by co9olguy** [comment]
Go for it!

**Pull request merged**
