### PR TITLE
Add a banner linking to the Catalyst blog post

### PR DESCRIPTION
**Pull request by josh146**
This is based on @WillXanadu's mockup:

image

### CODE REVIEW

**Comment by josh146** [comment]
PR preview: https://output.circle-artifacts.com/output/job/8def1fbd-b09e-4ea0-b134-d9996b9c3f50/artifacts/0/site/index.html

**Review by WillXanadu — COMMENTED** [review]
Hey @josh146 , the design of the banner in Figma was meant to stay sticky with the nav bar, until the user closes the banner—so there's a "close" button, as well as a slight drop shadow beneath the banner similar to the nav bar. Are we simplifying the design for this iteration? If so, happy to approve and revisit later!

**Review by Anakhom — APPROVED** [review]
Tested, looks good across all margins! Thank you

**Comment by Anakhom** [comment]
> Hey @josh146 , the design of the banner in Figma was meant to stay sticky with the nav bar, until the user closes the banner—so there's a "close" button, as well as a slight drop shadow beneath the banner similar to the nav bar. Are we simplifying the design for this iteration? If so, happy to approve and revisit later!

@josh146 in that case, `.banner` in `style.css` would look like this:

```
.banner {
  background: #0074e0;
  justify-content: center;
  align-items: center;
  text-align: center;
  position: fixed;
  width: 100%;
  z-index: 2;
}
```

**Comment by josh146** [comment]
@Anakhom thank you! I might not include the stickyness now, as I don't know how to include a 'close' button, which may make the stickyness annoying to users.

@WillXanadu this is a bit of a temporary addition - we would like a banner to advertise the Catalyst blog post, but as the new react site isn't live yet, it is being temporarily added to the old site in a minimal fashion.

Once the new site is up, the banner will match the behaviour you have above

**Comment by WillXanadu** [comment]
> @Anakhom thank you! I might not include the stickyness now, as I don't know how to include a 'close' button, which may make the stickyness annoying to users.
> 
> @WillXanadu this is a bit of a temporary addition - we would like a banner to advertise the Catalyst blog post, but as the new react site isn't live yet, it is being temporarily added to the old site in a minimal fashion.
> 
> Once the new site is up, the banner will match the behaviour you have above

Gotch, then this LGTM!

**Pull request merged**
