### PR TITLE
Update puzzles

### PR DESCRIPTION
**Pull request by branedrane**

### CODE REVIEW

**Review by josh146 — CHANGES_REQUESTED** [review]
Hey @branedrane! The new images have too much whitespace above/below the illustrations, so render oddly: 
image


Aside from that, looking good.

@larawatson, I recall you wanted to add 'by XXX' to the images?

**Comment by branedrane** [comment]
> Hey @branedrane! The new images have too much whitespace above/below the illustrations, so render oddly: image
> 
> Aside from that, looking good.
> 
> @larawatson, I recall you wanted to add 'by XXX' to the images?

Good point! Cropped images. Also, attributions are in the tooltip, but do we want something a bit more visible?

**Review by josh146 — APPROVED** [review]
Thanks @branedrane! looks great 💯

**Review by larawatson — COMMENTED** [review]
Thanks David!

**Pull request merged**
