### PR TITLE
Update devices plugins

### PR DESCRIPTION
**Pull request by KetpuntoG**
Removed the default.qubit.tf and default.qubit.autograd cards on this page: https://pennylane.ai/plugins.html

### CODE REVIEW

**Comment by isaacdevlugt** [comment]
Hmm still seems like it's there?
Screen Shot 2022-05-24 at 12 02 49 PM

**Comment by KetpuntoG** [comment]
> Hmm still seems like it's there?
> Screen Shot 2022-05-24 at 12 02 49 PM

I think you agave cache problems, try in another browser :)

**Comment by isaacdevlugt** [comment]
Voila! Fixed. Looks great!

**Review by isaacdevlugt — COMMENTED** [review]
Looks great!

**Review by isaacdevlugt — APPROVED** [review]
This is extraneous, but I didn't "approve" in my last review. Sorry!

**Pull request merged**
