### PR TITLE
Update ecosystem

### PR DESCRIPTION
**Pull request by co9olguy**
Adding more partners to ecosystem and modifying text/layout slightly

### CODE REVIEW

**Comment by AndrewGardhouse** [comment]
> At a certain width the IBM logo is on top of the google logo; when that happens the Unitary Fund logo also ends up too close to the Covestro logo though not actually on top of it.
> 
> Otherwise it looks fine, including on mobile.
> 

@jen-dodd I can take a look at this issue

**Comment by co9olguy** [comment]
Thanks @AndrewGardhouse, looks good to me! 

WIsh I could approve, but it's my own PR :laughing:

**Review by jen-dodd — COMMENTED** [review]
Definitely better and no overlaps that I can see. However I do notice that on mobile the logos get rather close together, which probably doesn't matter too much for the gaggle of partner orgs but I don't love it for the Xanadu / AWS logos at the top - they're close enough that they kind of look like one logo rather than two. Here are some screen shots for you.

File

File (1)

**Review by jen-dodd — APPROVED** [review]
Looks good to me now!

**Pull request merged**
